### Get the AuthorisationToken
### httpOnly: true <<----  ZA-komentowac te linijke w klasie AuthenticationService
POST http://localhost:3000/authentication/sign-in
Content-Type: application/json

{
  "email": "user1@nestjs.com",
  "password": "Password123"
}

### GET Coffees
GET http://localhost:3000/coffees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJlZnJlc2hUb2tlbklkIjoiYzIzOWYzMTMtOGFmYS00Y2MwLWFhZmItMGIwMzJiZWIyMDVkIiwiaWF0IjoxNjg1Nzg1MTkxLCJleHAiOjE2ODU4NzE1OTEsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.8R892u7TakELVAfvjKb0nsgsrvMTWRd3_2HX7lQqw8g


### GET Coffee with ID
GET http://localhost:3000/coffees/1234567890
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJlZnJlc2hUb2tlbklkIjoiYzIzOWYzMTMtOGFmYS00Y2MwLWFhZmItMGIwMzJiZWIyMDVkIiwiaWF0IjoxNjg1Nzg1MTkxLCJleHAiOjE2ODU4NzE1OTEsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.8R892u7TakELVAfvjKb0nsgsrvMTWRd3_2HX7lQqw8g

### Authorization by token. Use token to authorize. Token is valid 3600sek = 1hour
GET http://localhost:3000/coffees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJlZnJlc2hUb2tlbklkIjoiYzIzOWYzMTMtOGFmYS00Y2MwLWFhZmItMGIwMzJiZWIyMDVkIiwiaWF0IjoxNjg1Nzg1MTkxLCJleHAiOjE2ODU4NzE1OTEsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.8R892u7TakELVAfvjKb0nsgsrvMTWRd3_2HX7lQqw8g


### Authorization by REFRESH-token. Use refresh-token to authorize. Token is valid 86400sek = 24 Hours
POST http://localhost:3000/authentication/refresh-tokens
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJlZnJlc2hUb2tlbklkIjoiYzIzOWYzMTMtOGFmYS00Y2MwLWFhZmItMGIwMzJiZWIyMDVkIiwiaWF0IjoxNjg1Nzg1MTkxLCJleHAiOjE2ODU4NzE1OTEsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.8R892u7TakELVAfvjKb0nsgsrvMTWRd3_2HX7lQqw8g"
}

### Create a new Coffee <== accessToken and not the refreshToken
POST http://localhost:3000/coffees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlcjFAbmVzdGpzLmNvbSIsInJvbGUiOiJyZWd1bGFyIiwicGVybWlzc2lvbnMiOlsiY3JlYXRlX2NvZmZlZSJdLCJpYXQiOjE2ODU3ODUxOTEsImV4cCI6MTY4NTc4ODc5MSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.HWTnoGxkPsfD9YBf_KDA2xXPgNUK-yWy24shpbXUB_0
