### Get the AuthorisationToken
### httpOnly: true <<----  ZA-komentowac te linijke w klasie AuthenticationService
POST http://localhost:3000/authentication/sign-in
Content-Type: application/json

{
  "email": "user1@nestjs.com",
  "password": "Password123"
}

### GET Coffees
GET http://localhost:3000/coffees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJlZnJlc2hUb2tlbklkIjoiZWQxZjU4YWQtMjc4Yi00OTA5LTllYmItODFmZjU0ZjExNWQ3IiwiaWF0IjoxNjg1NzA3NDUyLCJleHAiOjE2ODU3OTM4NTIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.7_q0q6M_Bgy0Pjw_1U9CQG-6W_XZeOui1Vs9ZORdkKA


### GET Coffee with ID
GET http://localhost:3000/coffees/1234567890
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJlZnJlc2hUb2tlbklkIjoiZWQxZjU4YWQtMjc4Yi00OTA5LTllYmItODFmZjU0ZjExNWQ3IiwiaWF0IjoxNjg1NzA3NDUyLCJleHAiOjE2ODU3OTM4NTIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.7_q0q6M_Bgy0Pjw_1U9CQG-6W_XZeOui1Vs9ZORdkKA

### Authorization by token. Use token to authorize. Token is valid 3600sek = 1hour
GET http://localhost:3000/coffees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJlZnJlc2hUb2tlbklkIjoiZWQxZjU4YWQtMjc4Yi00OTA5LTllYmItODFmZjU0ZjExNWQ3IiwiaWF0IjoxNjg1NzA3NDUyLCJleHAiOjE2ODU3OTM4NTIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.7_q0q6M_Bgy0Pjw_1U9CQG-6W_XZeOui1Vs9ZORdkKA


### Authorization by REFRESH-token. Use refresh-token to authorize. Token is valid 86400sek = 24 Hours
POST http://localhost:3000/authentication/refresh-tokens
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJlZnJlc2hUb2tlbklkIjoiZWQxZjU4YWQtMjc4Yi00OTA5LTllYmItODFmZjU0ZjExNWQ3IiwiaWF0IjoxNjg1NzA3NDUyLCJleHAiOjE2ODU3OTM4NTIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.7_q0q6M_Bgy0Pjw_1U9CQG-6W_XZeOui1Vs9ZORdkKA"
}

### Create a new Coffee
POST http://localhost:3000/coffees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXNlcjFAbmVzdGpzLmNvbSIsInJvbGUiOiJyZWd1bGFyIiwicGVybWlzc2lvbnMiOlsiY3JlYXRlX2NvZmZlZSJdLCJpYXQiOjE2ODU3MDc0NTIsImV4cCI6MTY4NTcxMTA1MiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.MtQpppKFVB_q-JINMM6U--7r9X-Z0TkfpGqPtXcycWQ
